#!/bin/sh

# this should probably be a makefile but oh well
EXTENSION=$1
if test -z $1; then
    printf "Potential error: filetype defaulting to PDF.\nPlease provide a parameter with your desired file extension.\nContinuing...\n"
    EXTENSION=pdf
fi

mkdir -p docs/server &&
find -name '*.md' | sed 's/\.md$//g' | xargs -I filename pandoc filename.md -o docs/filename.$EXTENSION &&
echo 'Docs compiled successfully.'
